import Image from 'next/image'
import styles from './page.module.css'

export const metadata = {
  title: 'Home',
  description: 'Generated by create next app',
}

export default function Home() {
    return (
      <div>Home</div>
    )
}
