import Image from 'next/image'
import styles from './page.module.css'
import { get } from 'http'

export const metadata = {
  title: 'Home',
  description: 'Generated by create next app',
  
}

export default async function Home() {
    return (
      <>
        <div>Home</div>
        
      </>
    )
}